### PR TITLE
Add continuous learning scripts

### PR DESCRIPTION
**Pull request by javierron**
The `src/Continuous_Learning` folder contains a few scripts that automate the tokenizing of new data points and the incremental training of a model.

Signed-off-by: Javier Ron <javierron90@gmail.com>

### CODE REVIEW

**Comment by chenzimin** [comment]
Thank you for the PR, I am taking a look at it now.

**Comment by javierron** [comment]
> How is `src/Continuous_Learning/Defects4J_experiment.sh` different from `src/Defects4J_Experiment/Defects4J_experiment.sh`?

It is basically the same thing except for a few lines that store the number of found/compiled/passed patches into a .csv file, and also stores patches in a directory tagged with date.

If you think is better, I can implement those as optional features of the previous script before merging, I just didn't want to go around and changing scripts that are not mine. :+1:

**Comment by chenzimin** [comment]
LGTM, merged

**Comment by monperrus** [comment]
thanks Javier & Zimin!

**Pull request merged**
